FROM node:10
WORKDIR /app
COPY package.json package-lock.json /app/
RUN npm config set unsafe-perm true && npm install
ADD . /app
ENV NODE_ENV production
ENV HOST 0.0.0.0
EXPOSE 3000
ARG IS_TESTNET
ENV IS_TESTNET ${IS_TESTNET}
ARG RELEASE
ENV RELEASE ${RELEASE}
ARG FIREBASE_API_KEY
ENV FIREBASE_API_KEY ${FIREBASE_API_KEY}
ARG FIREBASE_AUTH_DOMAIN
ENV FIREBASE_AUTH_DOMAIN ${FIREBASE_AUTH_DOMAIN}
ARG FIREBASE_PROJECT_ID
ENV FIREBASE_PROJECT_ID ${FIREBASE_PROJECT_ID}
ARG INTERCOM_APPID
ENV INTERCOM_APPID ${INTERCOM_APPID}
ARG GTM_ID
ENV GTM_ID ${GTM_ID}
ARG SENTRY_PROJECT
ENV SENTRY_PROJECT ${SENTRY_PROJECT}
ARG SENTRY_DSN
ENV SENTRY_DSN ${SENTRY_DSN}
ARG SENTRY_AUTH_TOKEN
ENV SENTRY_AUTH_TOKEN ${SENTRY_AUTH_TOKEN}
ARG SENTRY_REPORT_URI
ENV SENTRY_REPORT_URI ${SENTRY_REPORT_URI}
RUN npm run build
USER 1337
CMD npm start
