FROM node:8
WORKDIR /app
COPY package.json package-lock.json /app/
RUN npm config set unsafe-perm true && npm install
ADD . /app
ENV NODE_ENV production
ENV HOST 0.0.0.0
EXPOSE 3000
ARG IS_TESTNET
ENV IS_TESTNET ${IS_TESTNET}
ARG RELEASE
ENV RELEASE ${RELEASE}
ARG INTERCOM_APPID
ENV INTERCOM_APPID ${INTERCOM_APPID}
ARG GA_TRACKING_ID
ENV GA_TRACKING_ID ${GA_TRACKING_ID}
ARG GTM_ID
ENV GTM_ID ${GTM_ID}
ARG STRIPE_TOKEN
ENV STRIPE_TOKEN ${STRIPE_TOKEN}
ARG SENTRY_PROJECT
ENV SENTRY_PROJECT ${SENTRY_PROJECT}
ARG SENTRY_DSN
ENV SENTRY_DSN ${SENTRY_DSN}
ARG SENTRY_AUTH_TOKEN
ENV SENTRSENTRY_AUTH_TOKENY_AUTH ${SENTRY_AUTH_TOKEN}
RUN npm run build
CMD npm start
